if (mtx == null) goto 04;
if (mtx.length != mtx[0].length) goto 04;
goto 05;
return false;
int n = mtx.length;
int r = 0;
if not (r < n) goto 20;
int c = 0;
if not (c < n) goto 18;
if (r == c) goto 13;
if (Math.abs(mtx[r][c] - 1) >= 1E-8) goto 13;
return false;
if not (r == c) and (Math.abs(mtx[r][c]) >= 1E-8) goto 15;
goto 16;
return false;
c++;
goto 09;
r++;
goto 07;
return true;